services:
  - type: web
    name: pdf-render
    runtime: docker
    plan: starter
    region: frankfurt
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,read_online_store_navigation
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
