# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c1adf1bf6c6d3295c778c14b9345b327"
application_url = "https://pdf-render-015q.onrender.com"
embedded = true
name = "pdf-render"

[access_scopes]
# Génération de catalogue = lecture seule (produits, collections, metafields).
scopes = "read_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://pdf-render-015q.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
